export * from './neophyte/multiply-numbers'
export * from './neophyte/combine-strings'
export * from './neophyte/equals'
export * from './neophyte/add-numbers'
export * from './neophyte/subtract-numbers'
